#!/usr/bin/env python3
"""Render the teightysix compare pair: one card, mint and forty years later.

	~/git/baseball-cards/baseball-cards/.venv/bin/python \
		scripts/render-teightysix-compare.py

Reads only from the parent card tool (`~/git/baseball-cards/baseball-cards`) and
writes only into `static/img/projects/teightysix/`. Nothing is written back into
the parent, and nothing there is committed.

THE SUBJECT is one of the parent's 196 invented dream86 players, not a real one.
The public side of this project is held to D13 (`teightysix/.claude/PLAN-RELEASE.md`
4.4): no real person's likeness generated by AI ships to strangers. Card 9000192
is "Rooster Vandiver", a generated right fielder in a blank 1980s uniform, and the
team bar carries the place name the public bench hands the parent
(`roster/dream/wordmarks.json`), never a club mark.

BOTH CARDS COME OFF ONE PRESS. The order of operations is pinned and identical
for the pair, so the only difference between them is time:

	frame86.render(wear=0, miscut=0)   the drawn front
	print86.apply(PRESS, seed=SEED)    the 1986 printing line: 122 LPI screen,
	                                   cyan/magenta a hair off register, dot gain
	frame86._miscut(MISCUT, SEED)      one blade cut one card, off centre
	frame86.age(WEAR, age=AGE)         WORN ONLY: yellowed board, faded dye,
	                                   chipped corners, pinholes, box-wall edge

compose86.py's own `--press` path presses AFTER the miscut, which slides the
geometric photo window out from under the screen; pressing first is what keeps
the two frames pixel-comparable and the halftone under the photograph.

EXPORT. webp keeps the alpha, so a corner that has worn away shows the page
through it. The PNG fallback is flattened onto the page's pale background and
palette-reduced, because a full-colour PNG of a halftone-and-grain card is a
megabyte and the whole image directory is held under 4 MiB.
"""
import argparse
import json
import pathlib
import sys

from PIL import Image, ImageOps

PARENT = pathlib.Path("~/git/baseball-cards/baseball-cards").expanduser()
OUT = pathlib.Path(__file__).resolve().parent.parent / "static/img/projects/teightysix"

# --- the recipe -------------------------------------------------------------
CARD_ID = 9000192          # dream86 "Rooster Vandiver", RF, Houston bar, follow-through
SEED = 9000197             # wear/press/cut seed, not the card id: this field has the
                           # box-wall bias on the left edge (wear86 BOXWALL_P), which is
                           # what forty years leaning on the side of a shoebox looks like
PRESS = 0.6                # print86 strength, both cards; the dream set's own value
MISCUT = 0.30              # 1986 Topps centring, as a fraction of the border
WEAR = 0.88                # hands: chipping, corners, pinholes, scuffs
AGE = 1.0                  # time: paper yellowing and dye fade, full forty years

# --- the export -------------------------------------------------------------
WEBP_W, WEBP_Q = 760, 76   # 2x the 380 px the card is shown at on a wide screen; q76 and q82
                           # are indistinguishable on a halftone card, and q76 is 70 KB cheaper
PNG_W, PNG_COLORS = 420, 128
PAGE_BG = (232, 240, 243)  # between --bg-mid #EEF4F6 and --bg-deep #E1ECEF


def framed_photo(frame86, rec):
	"""The dream portrait cropped and fitted to the photo window, exactly as
	compose86.compose does it: the measured head box first, then the window aspect."""
	pw = frame86.CARD_W - 2 * int(frame86.BORDER * frame86.CARD_W)
	ph = int(frame86.PHOTO_BOT * frame86.CARD_H) - int(frame86.BAR * frame86.CARD_H)
	with Image.open(PARENT / rec["path"]) as src:
		src = src.convert("RGB")
		if rec.get("crop"):
			src = src.crop(tuple(rec["crop"]))
		return ImageOps.fit(src, (pw, ph), method=Image.Resampling.LANCZOS,
		                    centering=tuple(rec.get("centering", [0.5, 0.0])))


def render(frame86, print86, rec, wordmark, wear, card_age):
	art = frame86.render(framed_photo(frame86, rec), rec["team"], rec["player"], rec["pos"],
	                     wear=0.0, miscut=0.0, seed=SEED, card_age=None,
	                     wordmark=wordmark, emblem_ink="white")
	mark = frame86.mark_box("86", frame86.EMBLEM_IMG)
	card = print86.apply(art, strength=PRESS, seed=SEED, mark=mark)
	card = frame86._miscut(card, MISCUT, SEED)
	if wear or card_age:
		card = frame86.age(card, wear, SEED, age=card_age)
	return card


def export(card, stem):
	card = card.convert("RGBA")
	web = card.resize((WEBP_W, round(WEBP_W * card.height / card.width)), Image.LANCZOS)
	web.save(OUT / f"{stem}.webp", quality=WEBP_Q, method=6)
	flat = Image.new("RGB", card.size, PAGE_BG)
	flat.paste(card, (0, 0), card)
	png = flat.resize((PNG_W, round(PNG_W * card.height / card.width)), Image.LANCZOS)
	png.quantize(colors=PNG_COLORS, method=Image.Quantize.FASTOCTREE,
	             dither=Image.Dither.FLOYDSTEINBERG).save(OUT / f"{stem}.png", optimize=True)
	for ext in ("webp", "png"):
		p = OUT / f"{stem}.{ext}"
		print(f"  {p.name:22s} {Image.open(p).size} {p.stat().st_size:>7,} B")


def main():
	ap = argparse.ArgumentParser()
	ap.add_argument("--native", help="also write the two 1000x1400 renders here")
	a = ap.parse_args()

	sys.path.insert(0, str(PARENT))
	import frame86, print86              # noqa: E402  (needs PARENT on the path first)

	rec = next(r for r in json.loads((PARENT / "roster/dream/manifest.json").read_text())
	           if r["id"] == CARD_ID)
	if not rec.get("reviewed"):
		raise SystemExit(f"dream card {CARD_ID} has not passed identity/framing review")
	bar = json.loads((PARENT / "roster/dream/wordmarks.json").read_text())["wordmarks"][
		frame86.team_key(rec["team"])]

	OUT.mkdir(parents=True, exist_ok=True)
	print(f'{rec["player"]}, {bar} {rec["pos"]}  seed {SEED}  press {PRESS}  miscut {MISCUT}')
	for stem, wear, card_age in (("compare-mint", 0.0, None), ("compare-worn", WEAR, AGE)):
		card = render(frame86, print86, rec, bar, wear, card_age)
		if a.native:
			native = pathlib.Path(a.native); native.mkdir(parents=True, exist_ok=True)
			card.save(native / f"{stem}-1000x1400.png")
		export(card, stem)

	total = sum(p.stat().st_size for p in OUT.rglob("*") if p.is_file())
	print(f"{OUT.relative_to(pathlib.Path(__file__).resolve().parent.parent)}: "
	      f"{total:,} B ({total / 1048576:.2f} MiB of the 4 MiB budget)")


if __name__ == "__main__":
	main()
